### ISSUE TITLE
extension.previewWechatApp

### ISSUE THREAD

**Issue by gexiaowei** [hellopao/vscode-wechat#2]
在mac下无法正常工作 预览时候出现extension.previewWechatApp

**Comment by gexiaowei** [comment]
wxss无法高亮

**Comment by cloudy064** [comment]
修改`$HOME/.vscode/extensions/qinjia.vscode-wechat-0.0.5/out/src/wechatApp.js`这个文件
把第九行
```js
const previewUri = vscode.Uri.parse(`file:///${previewContent}`);
```
修改为
```js
const previewUri = vscode.Uri.file(previewContent);
```
即可

**Comment by gexiaowei** [comment]
可以解决问题了，希望作者赶紧解决下

**Comment by gexiaowei** [comment]
然后还是预览不了，不知道是什么情况

**Comment by cloudy064** [comment]
wept模块有bug，单独运行这个模块有异常，没有深入研究，不知道为啥

**Comment by cloudy064** [comment]
刚刚研究了一下，解决了，办法如下：
打开`Terminal`，跳转到`~/.vscode/extensions/qinjia.vscode-wechat-0.0.5/node_modules/wept/bin`目录下，这里的`wcc`和`wcsc`没有执行权限所以会执行失败，所以你只需要执行
```
chmod +x wcc
chmod +x wcsc
```
就可以了

**Comment by gexiaowei** [comment]
刚在研究https://github.com/phodal/weapp-webdemo这2个文件呢，我试试看

**Comment by gexiaowei** [comment]
吐槽下 字体真难看，可以解决问题了

**Comment by gexiaowei** [comment]
更改以后 第一次加载失败 需要第二次加载

**Comment by chemzqm** [comment]
怎么可能文件没权限？vscode 干的吗？
